### PR TITLE
update people

### PR DESCRIPTION
**Pull request by chandanbhat**
update people.json

### CODE REVIEW

**Review by skprabhanjan — CHANGES_REQUESTED** [review]
Please don't add a new JSON, find your name and update it there

**Review by chandanbhat — COMMENTED** [review]
ok

**Review by skprabhanjan — CHANGES_REQUESTED** [review]
Please dont add a new JSON

**Comment by skprabhanjan** [comment]
@chandanbhat , Find your SRN and update your name there.
Dont add a new JSON,remove it

**Review by skprabhanjan — APPROVED** [review]

**Comment by skprabhanjan** [comment]
There are merge conflicts, please can you resolve it?

**Comment by chandanbhat** [comment]
I couldn't resolve this conflict..

**Review by chandanbhat — COMMENTED** [review]
is this correct??

**Comment by abhivijay96** [comment]
Hey there are too many conflicts, maybe because you reformatted the indentation, fork it again, make changes and open a new PR, closing #212

**Pull request closed without merging**
