### PR TITLE
Update people.json

### PR DESCRIPTION
**Pull request by nikitasingh1998**

### CODE REVIEW

**Review by AnaghHegde — CHANGES_REQUESTED** [review]
@nikitasingh1998 Great work  . Please add your name, where your SRN is present. Don't copy everything again. Take a look at #1 for reference.

**Review by skprabhanjan — CHANGES_REQUESTED** [review]
This is not the rite way to do it.

**Comment by nikitasingh1998** [comment]
E-mail id: itsmenikki1232@gmail.com
srn : 01FB16ECS473

**Comment by skprabhanjan** [comment]
Hey @nikitasingh1998 , good that you tried this considerably and that is what we are looking for.
I will add your name in the list of selected students, you can find it in the link which you can get in the Readme file.
So I will close this PR.
Closed #16

**Pull request closed without merging**
