### PR TITLE
Update people.json for 01fb16ecs107:deepali Prabhu

### PR DESCRIPTION
**Pull request by DeepaliP98**
task-1 PES POS

### CODE REVIEW

**Comment by NithinRama** [comment]
Please don't add a new JSON, find your SRN and update it.

**Comment by skprabhanjan** [comment]
Please send a new PR with updated code from the repo and the requested changes.
Closed #90.

**Comment by AnaghHegde** [comment]
@skprabhanjan  She didn't register. So i reopened the PR. @DeepaliP98 Please resolve the conflicts. Then its good to go.

**Review by skprabhanjan — CHANGES_REQUESTED** [review]
@DeepaliP98 ,Could please remove the two extra lines at 820 and 821.?

**Review by skprabhanjan — APPROVED** [review]

**Pull request merged**
