### PR TITLE
Update people.json

### PR DESCRIPTION
**Pull request by bilal-git**

### CODE REVIEW

**Review by skprabhanjan — CHANGES_REQUESTED** [review]
@bilal-git , please have the latest copy of the repo and then make one more commit to this same PR.

**Comment by skprabhanjan** [comment]
@bilal-git , Please send a new PR.
Closed #87

**Comment by bilal-git** [comment]
I do not know how to

**Comment by skprabhanjan** [comment]
Go to people.json, add your name and commit changes in your local forked copy and then send a PR to https://github.com/PesuOrg/ThirdSemFilter, just like you were doing before

**Pull request closed without merging**
