### PR TITLE
Added name-Vedartham Bharath

### PR DESCRIPTION
**Pull request by bharath-123**
Updated the json file to add my name.

### CODE REVIEW

**Review by skprabhanjan — APPROVED** [review]

**Comment by AnaghHegde** [comment]
Hi @bharath-123. It's good that you have completed the task this fast. I hope you know most of the FOSS things.

**Comment by skprabhanjan** [comment]
Closed #1

**Comment by bharath-123** [comment]
Thank you! I have done some basic contributions like contributing to a free programming books repository. I have contributed a little and raised issues to the free programming books repo. I also fork github repositories(online datasets,some good tutorials etc) and clone them to my machine to learn. I havent been able to contribute code though! I am not able to find a bug! I hope you guys can help me with that!

**Comment by skprabhanjan** [comment]
@bharath-123 , that's very good to know. We will surely help you to start  contributing to communities and fixing issues in their production code.

**Comment by AnaghHegde** [comment]
@bharath-123 That's awesome!! and you are still in 3rd semester. Like @skprabhanjan said we will definitely help you in all the ways we can. See you soon :)

**Comment by bharath-123** [comment]
Thanks guys!! :+1:

**Pull request merged**
