### PR TITLE
update

### PR DESCRIPTION
**Pull request by bilal-git**

### CODE REVIEW

**Comment by skprabhanjan** [comment]
Hey @bilal-git , the file was just updated, Please take look into it and commit your changes again

**Review by skprabhanjan — CHANGES_REQUESTED** [review]
@bilal-git , Lots of unnecessary changes found. Please change only your name and make sure you have the latest code

**Review by skprabhanjan — CHANGES_REQUESTED** [review]
Still there are lots of unnecessary changes, Please do it properly once again:)

**Review by AnaghHegde — CHANGES_REQUESTED** [review]
Pleas don't add new JSON. Add your name. Also resolve the conflicts. Then its good to go.

**Comment by AnaghHegde** [comment]
@bilal-git We really appreciate that you didn't give up. This is one of the thing that we look in the OSS contributors. Please keep this attitude of never giving up. This will definitely help you a lot. @skprabhanjan I think we can take him to the club.

**Comment by bilal-git** [comment]
Thanks alot.

**Comment by bilal-git** [comment]
Sorry to be disturbing you, but my name hasn't been added to the selected
students file.

**Comment by skprabhanjan** [comment]
Closed #192

**Pull request closed without merging**
